/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DefaultTable: typeof import('./src/components/DefaultTable.vue')['default']
    DevBar: typeof import('./src/components/DevBar.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FieldRenderer: typeof import('./src/components/form/FieldRenderer.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FormActionButtons: typeof import('./src/components/form/FormActionButtons.vue')['default']
    FormGenerator: typeof import('./src/components/form/FormGenerator.vue')['default']
    GroupContext: typeof import('./src/components/dashboard/GroupContext.vue')['default']
    GroupItems: typeof import('./src/components/dashboard/GroupItems.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemCard: typeof import('./src/components/dashboard/ItemCard.vue')['default']
    ItemCardSkeleton: typeof import('./src/components/dashboard/ItemCardSkeleton.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavigationTabs: typeof import('./src/components/NavigationTabs.vue')['default']
    OfflineBar: typeof import('./src/components/OfflineBar.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabListTabs: typeof import('./src/components/dashboard/TabListTabs.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanelGroups: typeof import('./src/components/dashboard/TabPanelGroups.vue')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
