# --- BUILD VUE APP ---
FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# --- FINAL NGINX RUNTIME ---
FROM nginx:alpine

# Build Output kopieren
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
EXPOSE 443
